### ISSUE TITLE
Remove Proxy Code and use new daprd app-channel flag

### ISSUE THREAD

**Issue by salaboy** [dapr-sandbox/dapr-ambient#14]
The `daprd` container now has a flag to proxy requests to external apps, so we need to use that instead of the proxy code that we have here. 

We need to remove the app channel proxy code located here: 

https://github.com/dapr-sandbox/dapr-ambient/blob/main/main.go#L91

Instead, we need to set up this new flag in the template: 

https://github.com/search?q=org%3Adapr+app-channel-address&type=code

`--app-channel-address`

**Comment by salaboy** [comment]
@mcruzdev Can you take care of this?

**Comment by mcruzdev** [comment]
Hi @salaboy, surely!
