### ISSUE TITLE
Add Helm-docs to the chart

### ISSUE THREAD

**Issue by salaboy** [dapr-sandbox/dapr-ambient#4]
Use something like: https://github.com/norwoodj/helm-docs to generate docs

**Comment by salaboy** [comment]
@mcruzdev this might be a good next step after we finish the important issues

**Comment by mcruzdev** [comment]
I think to do the following strategy:

```mermaid
flowchart LR
    A[Merge to main] -->|Executes| B(Generate Helm docs)
    B --> C(Push all changes to main)
```

It seems like https://github.com/bitnami/charts/blob/main/.github/workflows/generate-chart-readme.yml
