### ISSUE TITLE
Add gRPC support for app channel

### ISSUE THREAD

**Issue by salaboy** [dapr-sandbox/dapr-ambient#6]
Comment from @yaron2 

"we have this issue here which might be resolved for 1.11: https://github.com/dapr/dapr/issues/6177. this will enable us to set the app channel in daprd and remove the need to proxy the response back to the app.
if this doesn't get implemented, I suggest we use a standard Go net/http reverse proxy director to forward all traffic from daprd to the app endpoint. this should give us easy HTTP1.1/HTTP2 (gRPC) support"

**Comment by mcruzdev** [comment]
Hi @salaboy, this issue was solved by version `1.11.*`, I think that we can close it too 😄
